# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MacOS PaipuAnalyzer only test CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm
      run: |
        npm ci
        npm run-script package-darwin
    - name: cmake
      run: |
        git submodule update --init --recursive
        mkdir bin
        mkdir bin/release
        cd bin/release
        cmake ../.. -DCMAKE_BUILD_TYPE=Debug
        make -j
    - name: collect
      run: |
        cp -r dist/MajsoulPaipuCrawler-darwin-x64 result
        cp bin/release/PaipuAnalyzer result/
        cp bin/release/PaipuAnalyzer ./
        cp config.json result/
        cp PAADData.json result/
        cp doc/README.txt result/
        cp doc/release-notes.txt result/
        cp -r i18n result/
        ln -s "~/Library/Application Support/MajsoulPaipuAnalyzer/data" result/data
        ls -l result
        mv result MajsoulPaipuAnalyzer-macos
    - name: archive
      run: |
        brew install p7zip
        7z a PaipuAnalyzer.zip PaipuAnalyzer
    - uses: actions/upload-artifact@v2
      with:
        name: PaipuAnalyzer
        path: PaipuAnalyzer.zip
